variables:
  BAZEL_DIGEST_VERSION: "f670e9aec235aa23a5f068566352c5850a67eb93de8d7a2350240c68fcec3b25" # Bazel 3.4.1

build:
  tags:
    - docker
  image:
    name: gcr.io/cloud-marketplace-containers/google/bazel@sha256:$BAZEL_DIGEST_VERSION
    entrypoint: [""]
  stage: build
  script:
    - bazel --output_base output build //:package
    - rm modules/connector/naheulbook-api.js
    - cp dist/bin/modules/connector/naheulbook-api.js modules/connector/naheulbook-api.js
  artifacts:
    paths:
      - templates/**
      - assets/**
      - modules/**
      - styles/**/*.css
      - system.json
      - template.json
  cache:
    key: $BAZEL_DIGEST_VERSION
    paths:
      - node_modules
      - output
